### ISSUE TITLE
Howto in README.

### ISSUE THREAD

**Issue by wpoosanguansit** [NeQuissimus/zio-slf4j#22]
Hi,

Can you show how to use the library in README?  I did tried putting in the library and define App with Slf4jLogger, overwriting clazz and import scalaz's implicit for Show[String] but that still throws errors on def not found.  Thanks for your help.

**Comment by NeQuissimus** [comment]
I added a section to the README (which links into code), I hope that helps.

**Comment by NeQuissimus** [comment]
See https://github.com/NeQuissimus/zio-slf4j/blob/3e34ea042cb4bf621c815e73e37a28cb534ebf33/src/test/scala/sample.scala
