### ISSUE TITLE
How to provide the Logger to the env in v 0.1.8?

### ISSUE THREAD

**Issue by wpoosanguansit** [NeQuissimus/zio-slf4j#24]
Hi,

I am trying out following your example.  However, I am on Scala 2.11.X and I can only use v. 0.1.8.  With that, I am getting:

Error:(213, 22) type mismatch;
 found   : scalaz.zio.ZIO[nequi.zio.logger.Logger with scalaz.zio.console.Console with scalaz.zio.clock.Clock,Nothing,Int]
 required: scalaz.zio.ZIO[Environment,Nothing,Int]
    (which expands to)  scalaz.zio.ZIO[scalaz.zio.clock.Clock with scalaz.zio.console.Console with scalaz.zio.system.System with scalaz.zio.random.Random with scalaz.zio.blocking.Blocking,Nothing,Int]
    program(arr).fold(_ => 0, _ => 1) 

How do I provide Logger to the program?  Thanks for your help.

**Comment by NeQuissimus** [comment]
In the 0.1.x versions, you don't provide it in the environment. Instead, you mix in a logger. See https://github.com/NeQuissimus/zio-slf4j/blob/3e34ea042cb4bf621c815e73e37a28cb534ebf33/src/test/scala/sample.scala

**Comment by wpoosanguansit** [comment]
I did follow the example and it throws the example above.  In this case with v0.1. X, we don’t declare Logger as the env type?

**Comment by NeQuissimus** [comment]
That's right, you mix it into your application directly
